source 'https://rubygems.org'
gem 'rails',                    '4.2.0'
gem 'pg',                       '~>0.18.1'
gem 'sqlite3'
gem 'sass-rails',               '~> 5.0'
gem 'uglifier',                 '>= 1.3.0'
gem 'coffee-rails',             '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder',                 '~> 2.0'
gem 'sdoc',                     '~> 0.4.0', group: :doc
gem 'paperclip',                '~> 4.2.1'
gem 'faker',                    '~> 1.4.2'
gem "twitter-bootstrap-rails",  '~> 3.2.0'
gem 'bootstrap_form',           '~> 2.2.0'
gem 'bcrypt',                   '~> 3.1.7'
gem 'unicorn',                  '~> 4.8.3'
gem 'skylight',                 '~> 0.6.0'
gem "therubyracer",             '~> 0.12.1'
gem "less-rails",               '~> 2.6.0'
gem "rails_12factor",           '~> 0.0.3'
gem 'aws-sdk',                  '~> 1.5.7'
gem 'omniauth-twitter'
gem 'figaro'

group :development, :test do
  gem 'simplecov',              '~> 0.9.1'
  gem 'byebug'
  gem 'pry',                    '~> 0.10.1'
  gem "factory_girl_rails",     '~> 4.0'
  gem 'web-console',            '~> 2.0'
  gem 'spring',                 '~> 1.2.0'
  gem 'capybara',               '~> 2.4.4'
  gem 'mocha',                  '~> 1.1.0'
  gem 'launchy',                '~> 2.4.3'
  gem 'capybara_minitest_spec'
  gem 'database_cleaner',       '~> 1.4.0'
end
